authentication, login page, layout
na-webdev/BudgetifyApp pull request #8
Opened 2022-04-02 14:53 UTC by na-webdev

2022-04-04 06:55 UTC, AudriusBaltusis requested changes

2022-04-04 06:55 UTC, AudriusBaltusis commented on client/src/app/app-routing.module.ts
> +  // {
Please remove it

2022-04-04 06:55 UTC, AudriusBaltusis commented on client/src/app/app.component.ts
> +  get isLoggedIn() {
Please add return type everywhere

2022-04-04 06:55 UTC, AudriusBaltusis commented on client/src/app/app.component.ts
> +    window.addEventListener('click', (event) => {
Please create method for it

2022-04-04 06:55 UTC, AudriusBaltusis commented on client/src/app/auth/auth-form/auth-form.component.ts
> +    console.log(this.loginForm.value);
Please remove `console.log`

2022-04-04 06:55 UTC, AudriusBaltusis commented on client/src/app/auth/services/auth.service.ts
> +  private setSession(res: any) {
Please do not use `any`

2022-04-04 06:55 UTC, AudriusBaltusis commented on client/src/app/home/components/home/home.component.ts
> +    alert('income added');
Please look for another option to show success message

2022-04-04 06:55 UTC, AudriusBaltusis commented on client/src/app/layout/header/header.component.ts
> +  onClick() {
Please add return type

2022-04-04 07:00 UTC, na-webdev commented
Hi, ok I will fix them. Thank you

2022-04-06 21:22 UTC, na-webdev commented
Hi, I hope I fixed all issues

2022-04-07 14:55 UTC, AudriusBaltusis approved these changes

2022-04-07 15:06 UTC, merged