Account
na-webdev/BudgetifyApp pull request #9
Opened 2022-04-11 03:12 UTC by na-webdev

2022-04-11 03:17 UTC, na-webdev commented
Hi, how are you doing?  Below lecturer gave these tasks as homework. If I am not mistaken I have already done the homework for this week in my last auth-page pull request review.

1. Separate logic from the main and login page into components
2. Add all static pages
3. Backlog work

2022-04-11 12:11 UTC, AudriusBaltusis requested changes

2022-04-11 12:11 UTC, AudriusBaltusis commented on client/src/app/account/components/account-card-list/account-card-list.component.ts
> +  ngOnInit(): void {}
Please remove redundant `ngOnInit`

2022-04-11 12:11 UTC, AudriusBaltusis commented on client/src/app/account/components/account-card-list/account-card-list.component.ts
> +    dialogRef.afterClosed().subscribe((result) => {
It looks redundant

2022-04-11 12:11 UTC, AudriusBaltusis commented on client/src/app/account/components/account-card-list/account-card-list.component.ts
> +  cardTrackingFn(index: number, item: AccountInterface) {
Please add return type

2022-04-11 12:11 UTC, AudriusBaltusis commented on client/src/app/account/components/dialogue/dialogue.component.ts
> +  onSubmit() {
return type

2022-04-11 12:11 UTC, AudriusBaltusis commented on client/src/app/account/components/dialogue/dialogue.component.ts
> +      .subscribe(
You have to unsubscribe, or use `takeUntil()`

2022-04-11 12:11 UTC, AudriusBaltusis commented on client/src/app/account/components/dialogue/dialogue.component.ts
> +    return this.addAccountForm.get('title')!.errors?.['required']
I suggest to use `switch ... case` here

2022-04-11 12:11 UTC, AudriusBaltusis commented on client/src/app/account/services/account.service.ts
> +  accountsUpdated = new Subject<AccountInterface[]>();
Seems it's private

2022-04-11 12:11 UTC, AudriusBaltusis commented on client/src/app/account/services/account.service.ts
> +          this.accounts.push({
In this case better to call `requestUserAccounts` from component to keep account list up to date, than leave this responsibility to `addNewAccount`.

2022-04-12 19:17 UTC, na-webdev commented on client/src/app/account/components/dialogue/dialogue.component.ts
> +      .subscribe(
fixed

2022-04-12 19:19 UTC, na-webdev commented on client/src/app/account/components/dialogue/dialogue.component.ts
> +    return this.addAccountForm.get('title')!.errors?.['required']
get title errors giving object like this {required: true} or {pattern: true} checking with ternary operator or with if statement is better I think

2022-04-13 05:53 UTC, na-webdev commented
Hi, how are you? 
I hope my code doesn't have serious problems

2022-04-13 07:32 UTC, AudriusBaltusis approved these changes

2022-04-13 07:49 UTC, merged